### ISSUE TITLE
Initial warning pop-up has "CANCEL" button

### ISSUE THREAD

**Issue by shihaamabr** [sunilpaulmathew/De-Bloater#10]
It should be an "OK" button

**Comment by sunilpaulmathew** [comment]
@shihaamabr  @WhoIsFishie
I personally want to show and **Accept** or **Agree** button and prevent using app if users opt **Cancel**. However, some people claimed that its against GPL. Now it is just a formal message just to let the users know the possible danger. As long as the button doesn't do anything except dismissing the dialog, I really don't think it is necessary to change it.
