### ISSUE TITLE
Question : does the module blocks app thats installed with the same package name

### ISSUE THREAD

**Issue by yant0** [sunilpaulmathew/De-Bloater#13]
i have instagram as bloat
i want to delete instagram
i delete instagram through debloater app
i want to install instagram (new)
???

**Comment by sunilpaulmathew** [comment]
> i have instagram as bloat i want to delete instagram i delete instagram through debloater app i want to install instagram (new) ???

You can install it as a normal user app. De-Bloater doesn't block anything except systemles-ly replace the APK in /system partion.

**Comment by yant0** [comment]
okay
