### ISSUE TITLE
Add packageName to Active application view

### ISSUE THREAD

**Issue by anuraag488** [sunilpaulmathew/De-Bloater#14]
Hi
Thanks for this app. Can you add package names to application list view and if possible to search.

**Comment by sunilpaulmathew** [comment]
@anuraag488 
It is definitely possible. However, I personally found its more useful to show to the APK path, than package name. Moreover, De-Bloater is bot doing much things with the package name. We always use APK path. Still, thanks for the suggestion.

**Comment by anuraag488** [comment]
Ok it's upto you.
One question - if i debloat some xyz app then deleting that app from /data/adb/modules/De-bloater/system will restore that app?

**Comment by sunilpaulmathew** [comment]
> /data/adb/modules/De-bloater/system

If you delete "/data/adb/modules/De-bloater/system", every debloated apps will be restored, but only after a reboot.

**Comment by anuraag488** [comment]
> > /data/adb/modules/De-bloater/system
> 
> If you delete "/data/adb/modules/De-bloater/system", every debloated apps will be restored, but only after a reboot.

I mean if one app inside system folder then that app will be restored?

**Comment by sunilpaulmathew** [comment]
> > > /data/adb/modules/De-bloater/system
> > 
> > 
> > If you delete "/data/adb/modules/De-bloater/system", every debloated apps will be restored, but only after a reboot.
> 
> I mean if one app inside system folder then that app will be restored?

Yes. But again, after a reboot.

**Comment by anuraag488** [comment]
> Yes. But again, after a reboot.
Thank you. I am looking to do that through recovery just in case i get bootloop.

**Comment by anuraag488** [comment]
@sunilpaulmathew thanks for adding package name. Can you further add it to search.

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew thanks for adding package name. Can you further add it to search.

I'll try. Don't know when I'll touch this app again. I reopened this issue, and added an "enhancement'" label.

**Comment by yephny** [comment]
I agree that searching for an app with their package name is useful, especially when there is a common keyword that's present in the package names of all of the apps you want to "uninstall" using De-Bloater, like all apps that have google in their package name.
