### ISSUE TITLE
Misleading UI after applying script

### ISSUE THREAD

**Issue by glemco** [sunilpaulmathew/De-Bloater#18]
Everything worked fine after applying the Tomatot script, however the the confirmation alert shows CANCEL (in Italian ANNULLA) instead of OK.
Pressing the button didn't change anything and the process worked, but it got me a little confused.
I'm not familiar with android, but considering there's no ANNULLA in the Italian text resources, I suppose that's an automated button due to the fact there's just one (however I'd suppose on an alert message with just one button, that one would be confirm).
Screenshot is attached.
![Screenshot_20220206-103503](https://user-images.githubusercontent.com/32201227/152676476-f009caec-5a75-45c1-97a9-08eeeddc47d6.jpg)

**Comment by glemco** [comment]
Same as #10

**Comment by sunilpaulmathew** [comment]
@glemco 
Thanks. I shall replace that button with an **Okay** or **Close** in future.
