### ISSUE TITLE
path /system/preload

### ISSUE THREAD

**Issue by RV7PR** [sunilpaulmathew/De-Bloater#23]
Shouldn't /system/preload be included as a path?

![Screenshot_20220529-105240_Solid Explorer](https://user-images.githubusercontent.com/17615589/170860839-0edd3501-345d-4d2a-99d8-dd4487abce83.jpg)

**Comment by sunilpaulmathew** [comment]
@RV7PR 
I'll try. It will most probably work as it is inside /system folder.
