### ISSUE TITLE
Backup Inactive Debloat List Not Working

### ISSUE THREAD

**Issue by jhrush** [sunilpaulmathew/De-Bloater#26]
On Android 11 De-bloater states "Backup files is created as /storage/emulated/0/deviceName.json"

The json file is nowhere to be found. I suggest that the app is updated to allow the user to specify the name of the file.

**Comment by sunilpaulmathew** [comment]
@jhrush 
Thanks for this issue. Are you sure it is not working. I don't see any reasons for failing it. But, certainly, I'll have a look on it.

By the way, have you tried using the share option appear right after the backup?

**Comment by sunilpaulmathew** [comment]
> Yes the share option produces a file that is 0 bytes in size and immediately fails, I tried to share with services such as signal, bluetooth, email. I think it might have something to do with special characters as my device name has '()' in it

Yes, it will be a potential reason. I'll solve it in future. Thanks again.
