### ISSUE TITLE
how to "delete '/data/adb/modules/De-bloater' via recovery."?

### ISSUE THREAD

**Issue by kekeqwq** [sunilpaulmathew/De-Bloater#35]
In recovery mode, can't use adb:
```
$ adb devices
List of devices attached
00000       unauthorized
```
```
$ adb shell "rm /data/adb/modules/De-bloater"
adb: device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.
```

**Comment by ivan-zaera** [comment]
In theory a factory reset should do it since /data is the userdata partition (see https://www.addictivetips.com/mobile/android-partitions-explained-boot-system-recovery-data-cache-misc/)

**Comment by ivan-zaera** [comment]
If you try it, can you confirm that it works? Thx

**Comment by ivan-zaera** [comment]
Or try this ;-) -> https://www.thecustomdroid.com/uninstall-magisk-modules-in-twrp-recovery-guide/

**Comment by KalyaSc** [comment]
It may be to late for me and kekeqwq, but In case someone else comes across this post with a Magisk rooted phone (where su with ADB is not possible in safe mode):

- Turn your smartphone off and turn it back on and directly press and hold the volume down button to boot into safe mode (It's a VERY long press, it should display "safe mode" in the bottom left corner)
- Enable USB debugging and connect it to your PC
- run `adb devices` and authorize your phone
- run `adb wait-for-device shell magisk --remove-modules`

This should remove all your installed modules and reboot your phone :). This is what worked for me on Samsung A53 14. If it still doesn't work here's the source where I found my solution and another method:

https://xdaforums.com/t/delete-magisk-module-from-bootlooping-phone.4405815/
