### ISSUE TITLE
Xaomi UAD script disabled

### ISSUE THREAD

**Issue by ngenx** [sunilpaulmathew/De-Bloater#4]
The Universal Android Debloater script says it's "disabled" and lists no applications. The script on PC works fine.

Redmi Note 7
Not running MIUI

Thanks

**Comment by sunilpaulmathew** [comment]
I know that UAD implementation is not perfect. However, the "disabled" status clearly says the script is not applied. If it is applied it says something like "This script is currently enabled" or something. Also, the Apply button will be replaced with a Restore button. Please check out [this](https://czuvpraze-my.sharepoint.com/:i:/g/personal/menacherry_af_czu_cz/EYhlBUZ_IN9KiIBhsVDTe8IBXVpKjTjlZM2ocs0HT0ToKA?e=oVM9xG) screenshot.
