### ISSUE TITLE
system apps on system_ext

### ISSUE THREAD

**Issue by Davpyu** [sunilpaulmathew/De-Bloater#8]
are there any ways to remove system apps on system_ext/ ?

**Comment by sunilpaulmathew** [comment]
@Davpyu 
Impossible at this moment. However, definitely possible if Magisk allowed to systems-lessly replace folder/files from that folder. Do you think it's possible to test in your end? I do not have any apps inside that place (in my phone).

**Comment by Davpyu** [comment]
i can test it if you want. the other way i use to remove system apps on system_ext is using gapps trash remover via twrp, and i need to edit the script so i can remove some apps which is kinda annoying.

**Comment by sunilpaulmathew** [comment]
> sing gapps trash remover via twrp,

In that case, can you do the following?
1. Debloat some unwanted apps (at least one, to initiate debloater module) using the app. It will then create a new folder at "/data/adb/modules/De-bloater" (skip this step if you are already debloated something with this app).
2. Inside that folder, create the following folder and files.
     **system_ext**/**APP**/**APK.apk** where
     i. **APP** is the name of the folder in which the apk file to be debloated is located and
     ii. **APK.apk** is the name of the APK file to be debloated.
3. Reboot and check the specific app is removed.

**Comment by Davpyu** [comment]
> > sing gapps trash remover via twrp,
> 
> In that case, can you do the following?
> 
> 1. Debloat some unwanted apps (at least one, to initiate debloater module) using the app. It will then create a new folder at "/data/adb/modules/De-bloater" (skip this step if you are already debloated something with this app).
> 2. Inside that folder, create the following folder and files.
>    **system_ext**/**APP**/**APK.apk** where
>    i. **APP** is the name of the folder in which the apk file to be debloated is located and
>    ii. **APK.apk** is the name of the APK file to be debloated.
> 3. Reboot and check the specific app is removed.

not working after all
![Screenshot_20210602-172443](https://user-images.githubusercontent.com/42276243/120464824-8c055500-c3c7-11eb-8dea-f56fd47c8664.png)

**Comment by sunilpaulmathew** [comment]
> > > sing gapps trash remover via twrp,
> > 
> > 
> > In that case, can you do the following?
> > 
> > 1. Debloat some unwanted apps (at least one, to initiate debloater module) using the app. It will then create a new folder at "/data/adb/modules/De-bloater" (skip this step if you are already debloated something with this app).
> > 2. Inside that folder, create the following folder and files.
> >    **system_ext**/**APP**/**APK.apk** where
> >    i. **APP** is the name of the folder in which the apk file to be debloated is located and
> >    ii. **APK.apk** is the name of the APK file to be debloated.
> > 3. Reboot and check the specific app is removed.
> 
> not working after all
> ![Screenshot_20210602-172443](https://user-images.githubusercontent.com/42276243/120464824-8c055500-c3c7-11eb-8dea-f56fd47c8664.png)

I mean, can you replace that APK with an empty text file with the exact same name (

**Comment by Davpyu** [comment]
> > > > sing gapps trash remover via twrp,
> > > 
> > > 
> > > In that case, can you do the following?
> > > 
> > > 1. Debloat some unwanted apps (at least one, to initiate debloater module) using the app. It will then create a new folder at "/data/adb/modules/De-bloater" (skip this step if you are already debloated something with this app).
> > > 2. Inside that folder, create the following folder and files.
> > >    **system_ext**/**APP**/**APK.apk** where
> > >    i. **APP** is the name of the folder in which the apk file to be debloated is located and
> > >    ii. **APK.apk** is the name of the APK file to be debloated.
> > > 3. Reboot and check the specific app is removed.
> > 
> > 
> > not working
> I mean, can you replace that APK with an empty text file with the exact same name (Music.apk). Also, please note that everything is case sensitive.

i've tried like what you said, but it didnt work, also i've match the folder and app name because i know it would be case sensitive

**Comment by sunilpaulmathew** [comment]
> > I mean, can you replace that APK with an empty text file with the exact same name (Music.apk). Also, please note that everything is case sensitive.
> 
> i've tried like what you said, but it didnt work, also i've match the folder and app name because i know it would be case sensitive

Okay, just to confirm, can you check the respective app is uninstall-able. Because, sometimes, even the app after the app was debloated, a local update will exist. Thanks a lot for the testing, anyway.

**Comment by Davpyu** [comment]
it cant be uninstalled

**Comment by sunilpaulmathew** [comment]
> it cant be uninstalled

Then, probably it is beyond the scope of Magisk (and hence this app too).

**Comment by dimqua** [comment]
@sunilpaulmathew I am able to debloat apps installed in `system_ext` using [Debloater (Terminal Emulator)](https://github.com/Magisk-Modules-Repo/terminal_debloater) module by specified a custom directory ( such as `/system/system_ext/priv-app/` or `/system/system_ext/app/`).

It can't debloat apps from folders inside `/system_ext/` though, but at least on my system (LineageOS 18.1), it's just a symlink to `/system/system_ext/`.

Could you add a possibility to debloat apps inside `/system/system_ext/*` folders, please?

**Comment by Davpyu** [comment]
oh yeah, thats how gapps trash remover remove from system_ext

**Comment by sunilpaulmathew** [comment]
> @sunilpaulmathew I am able to debloat apps inside `/system_ext` using [Debloater (Terminal Emulator)](https://github.com/Magisk-Modules-Repo/terminal_debloater) module by specifying a custom directory (such as `/system/system_ext/priv-app/` or `/system/system_ext/app/`).
> 
> It can't debloat apps inside `/system_ext/` directory directly though, but at least on my system (LineageOS 18.1), it's just a symlink to `/system/system_ext/`.
> 
> Could you add a possibility to debloat apps inside `/system/system_ext/` directory, please?

You mean, /system_ext is symlinked to /system/system_ext? In that case, we can also do that? We are doing a similar technique for apps inside /products.

**Comment by Davpyu** [comment]
yes @sunilpaulmathew like that, mostly use symlink

**Comment by sunilpaulmathew** [comment]
> yes @sunilpaulmathew like that, mostly use symlink

Then, I'll definitely have a look at it in the near future. Please stay tuned.

**Comment by sunilpaulmathew** [comment]
@Davpyu @dimqua 
Any chance to test and see if the [attached version of APK](https://www.dropbox.com/s/d1uj7mikyf8lojb/com.sunilpaulmathew.debloater.apk?dl=0) is able to see and debloat application inside **/system_ext/app** and **/system_ext/priv-app** folders. I can't do it myself here. My phone even do not have that folder. Thank you.

**Comment by sunilpaulmathew** [comment]
Closing this issue with the hope that v0.17 will solve it. If not, feel free to reopen it.

**Comment by dimqua** [comment]
Works for me. Thanks!

**Comment by Davpyu** [comment]
it works on me too, thank you @sunilpaulmathew
